# Generated by Django 6.0.1 on 2026-01-16 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_lenght_post_weight'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='lenght',
            new_name='length',
        ),
    ]
